const Strings = {
  allProductSell: "All Products on SALE!",
  allProductSellDescription:
    "All Products listed on F&F Bargains are on Sale compared to Amazon with same Quality.",
  next: "Next",
  productAtyour: "Products at your Fingertips",
  productAtyourDesc:
    "Explore Products. Easy Cart Management. Secure Payments. Track Your Orders.  ",
  WelcomeBack: "Welcome Back!",
  email: "Email",
  password: "Password",
  forgotPass: "Forgot Password?",
  reset: " Reset",
  dontAccount: "Don’t have an Account? ",
  register: "Register",
  pinkBabies: "Pink Babies",
  teddyBear: "Teddy Bear for babies",
  newestArrivals: "Newest Arrivals🔥",
  flash: "Flash Sale ⚡",
  viewAll: "View all",
  searchByProduct: "Search By Product Brand",
  openModal: "Open Modal",
  login: "Login",
  product: "Product",
  profile: "Profile",
  orderHistory: "Order History",
  giftCard: "Gift Cards",
  referandEarn: "Refer & Earn",
  address: "Delivery Address",
  setting: "Settings",
  waffels: "Waffels",
  applyKoalafi: "Apply koalafi",
  editProfile: "Edit Profile",
  liveAuction: "Live Auctions",
  ffsteals: "F&F Steal Deals",
  paymentMethods: "Payment Methods",
  tail: "tail",
};

export default Strings;
