import { Dimensions } from "react-native";
import PriceDetails from "../component/PriceDetails";
import PickupLocation from "../component/PickupLocation";
import DeliveryAddress from "../screen/DeliveryAddress";

const Strings = {
  name: "Name",
  allProductSell: "All Products on SALE!",
  city: "City",
  allProductSellDescription:
    "All Products listed on F&F Bargains are on Sale compared to Amazon with same Quality.",
  next: "Next",
  productAtyour: "Products at your Fingertips",
  productAtyourDesc:
    "Explore Products. Easy Cart Management. Secure Payments. Track Your Orders.  ",
  WelcomeBack: "Welcome Back!",
  email: "Email",
  password: "Password",
  forgotPass: "Forgot Password?",
  reset: " Reset",
  dontAccount: "Don’t have an Account? ",
  register: "Register",
  pinkBabies: "Pink Babies",
  teddyBear: "Teddy Bear for babies",
  newestArrivals: "Newest Arrivals🔥",
  flash: "Flash Sale ⚡",
  viewAll: "View all",
  searchByProduct: "Search By Product Brand",
  openModal: "Open Modal",
  login: "Login",
  product: "Product",
  profile: "Profile",
  orderHistory: "Order History",
  giftCard: "Gift Cards",
  referandEarn: "Refer & Earn",
  address: "Delivery Address",
  setting: "Settings",
  waffels: "Waffels",
  applyKoalafi: "Apply koalafi",
  editProfile: "Edit Profile",
  liveAuction: "Live Auctions",
  ffsteals: "F&F Steal Deals",
  paymentMethods: "Payment Methods",
  tail: "tail",
  aboutus: "About Us",
  contactus: "Contact Us",
  refundAndCancelation: "Refund & Cancellation",
  privacyPolicy: "Privacy Policy",
  termsAndConditions: "Terms & Conditions",
  pleaseWait: "Please Wait",
  logout: "Logout",
  deleteAccount: "Delete Account",
  version: "Version: 1.5 (5)",
  areYouSure: "Are you Sure?",
  areYouSureLogOut: "Are you sure you want to Logout?",
  youWillLoginAgain: "You will have to Login again.",
  cancel: "Cancel",
  confirmLogout: "Confirm Logout!",
  productDetails: "Product Details",
  weight: "Weigth",
  dimension: "Dimension",
  brand: "Brand",
  quantity: "Quantity",
  addToCart: "ADD TO CART",
  buyNow: "BUY NOW",
  selectSize: "Select Size",
  defaultImage: "https://cdn-icons-png.flaticon.com/128/4131/4131708.png",
  remove: "Remove",
  delivery: "Delivery",
  pickup: "Pickup",
  selectLocation: "Select your nearest pickup location",
  priceDetails: "Price Details",
  promoCode: "Promo Code",
  viewDetails: "View Details",
  placeOrder: "Place Order",
  deliveryTo: "Delivery To",
  change: "Change",
  profileInfo: "Profile Info",
  defaultPickupLocation: "Default Pickup Location",
  pending: "Pending",
  confirmed: "Confirmed",
  itemApprovede: "Items Approved",
  itemRejected: "Items Rejected",
  orederdOn: "Ordered On",
  on: "On",
  items: "Items",
  orderDetails: "Order Details",
  orderReceipt: "Order Receipt",
  orderSummary: "Order Summary",
  orderStatus: "Order Status",
  deliveryType: "Delivery Type",
  pickupLocation: "Pickup Location",
  paymentStatus: "payment Status",
  customerContactdetail: "Customer Contact Detail",
  phoneNumber: "Phone Number",
  addressOrder: "Address",
  detail: "Details",
  paymentsummary: "Payment Summary",
  grandTotal: "Grand Total",
  taxAmount: "Tax Amount",
  taxExempt: "Tax Exempt",
  giftCardOrder: "Gift Card",
  deliveryFee: "Delivery Fee",
  discount: "Discount",
  payableAmount: "Payable Amount",
  si: "SI",
  qty: "Qty",
  price: "Price",
  status: "Status",
  refund: "Refund",
  refunded: "Refunded",
  rejectreason: "Reject Reason",
  deliveryAddress: "Delivery Address",
  addressInfo: "Address Info",
  streetAddress: "Street Address",
  countryAbbreviation: "Country Abbreviation",
  stateAbbreviation: "State Abbreviation",
  zipCode: "ZIP Code",
  saveAddress: "Save Address",
};

export default Strings;
